import json
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

from app.database.session import get_db
from app.models.database_models import Dataset


router = APIRouter()


BASE_DIR = Path(__file__).resolve().parents[2]
REPORT_DIR = BASE_DIR / "reports"
REPORT_DIR.mkdir(exist_ok=True)


def get_report_path(report_id: str):
    return REPORT_DIR / f"{report_id}.json"


def load_prediction_report(report_id: str):
    report_path = get_report_path(report_id)

    if not report_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Prediction report not found.",
        )

    with open(report_path, "r", encoding="utf-8") as file:
        return json.load(file)


def clean_pdf_text(value):
    text = str(value)
    text = text.replace("\\", "\\\\")
    text = text.replace("(", "\\(")
    text = text.replace(")", "\\)")
    text = text.replace("\n", " ")
    return text


def wrap_text(text, limit=90):
    words = str(text).split()
    lines = []
    current = ""

    for word in words:
        if len(current) + len(word) + 1 <= limit:
            current = f"{current} {word}".strip()
        else:
            if current:
                lines.append(current)
            current = word

    if current:
        lines.append(current)

    return lines


def add_pdf_line(lines, text="", size=11):
    for wrapped_line in wrap_text(text):
        lines.append((wrapped_line, size))


def build_simple_pdf(lines, output_path: Path):
    page_width = 595
    page_height = 842
    margin_x = 45
    start_y = 800
    line_gap = 17

    pages = []
    current_page = []
    y = start_y

    for text, size in lines:
        if y < 55:
            pages.append(current_page)
            current_page = []
            y = start_y

        current_page.append((text, size, margin_x, y))
        y -= line_gap

    if current_page:
        pages.append(current_page)

    objects = []

    objects.append("<< /Type /Catalog /Pages 2 0 R >>")

    page_object_numbers = []
    content_object_numbers = []

    font_object_number = 3
    next_object_number = 4

    for _ in pages:
        page_object_numbers.append(next_object_number)
        next_object_number += 1
        content_object_numbers.append(next_object_number)
        next_object_number += 1

    kids = " ".join([f"{number} 0 R" for number in page_object_numbers])
    objects.append(f"<< /Type /Pages /Kids [{kids}] /Count {len(pages)} >>")

    objects.append("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    for page_index, page in enumerate(pages):
        page_obj_num = page_object_numbers[page_index]
        content_obj_num = content_object_numbers[page_index]

        page_object = (
            f"<< /Type /Page /Parent 2 0 R "
            f"/MediaBox [0 0 {page_width} {page_height}] "
            f"/Resources << /Font << /F1 {font_object_number} 0 R >> >> "
            f"/Contents {content_obj_num} 0 R >>"
        )

        stream_lines = []

        for text, size, x, y in page:
            escaped = clean_pdf_text(text)
            stream_lines.append(
                f"BT /F1 {size} Tf {x} {y} Td ({escaped}) Tj ET"
            )

        stream = "\n".join(stream_lines)

        content_object = (
            f"<< /Length {len(stream.encode('utf-8'))} >>\n"
            f"stream\n{stream}\nendstream"
        )

        objects.append(page_object)
        objects.append(content_object)

    pdf_parts = ["%PDF-1.4\n"]
    offsets = []

    for index, obj in enumerate(objects, start=1):
        offsets.append(len("".join(pdf_parts).encode("utf-8")))
        pdf_parts.append(f"{index} 0 obj\n{obj}\nendobj\n")

    xref_offset = len("".join(pdf_parts).encode("utf-8"))

    pdf_parts.append(f"xref\n0 {len(objects) + 1}\n")
    pdf_parts.append("0000000000 65535 f \n")

    for offset in offsets:
        pdf_parts.append(f"{offset:010d} 00000 n \n")

    pdf_parts.append(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF"
    )

    output_path.write_bytes("".join(pdf_parts).encode("utf-8"))


def create_pdf_report(report_data: dict, report_id: str):
    pdf_path = REPORT_DIR / f"{report_id}.pdf"

    lines = []

    add_pdf_line(lines, "ADP AI - Prediction Report", 18)
    add_pdf_line(lines, "Generated by ADP AI Random Forest Prediction Pipeline", 11)
    add_pdf_line(lines, "-" * 80, 10)

    add_pdf_line(lines, f"Report ID: {report_id}", 11)
    add_pdf_line(lines, f"Algorithm: {report_data.get('algorithm', 'N/A')}", 11)
    add_pdf_line(lines, f"Model Type: {report_data.get('model_type', 'N/A')}", 11)
    add_pdf_line(lines, f"Accuracy Score: {report_data.get('accuracy_score', 'N/A')}%", 11)

    dataset_details = report_data.get("dataset_details", {})
    model_selection = report_data.get("model_selection", {})

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Dataset Details", 14)
    add_pdf_line(lines, f"Target Column: {dataset_details.get('target_column', 'N/A')}", 11)
    add_pdf_line(lines, f"Total Rows: {dataset_details.get('total_rows', 'N/A')}", 11)
    add_pdf_line(lines, f"Total Columns: {dataset_details.get('total_columns', 'N/A')}", 11)

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Model Selection", 14)
    add_pdf_line(lines, f"AI Detected Intent: {model_selection.get('ai_detected_intent', 'N/A')}", 11)
    add_pdf_line(lines, f"Final Task Type: {model_selection.get('final_task_type', 'N/A')}", 11)
    add_pdf_line(lines, f"Decision Reason: {model_selection.get('decision_reason', 'N/A')}", 11)

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Metrics", 14)
    metrics = report_data.get("metrics", {})
    for key, value in metrics.items():
        add_pdf_line(lines, f"{key}: {value}", 11)

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Top Feature Importance", 14)
    feature_importance = report_data.get("feature_importance", [])

    for item in feature_importance[:15]:
        feature = item.get("feature", "N/A")
        importance = item.get("importance", "N/A")
        add_pdf_line(lines, f"{feature}: {importance}", 11)

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Prediction Samples", 14)
    prediction_samples = report_data.get("prediction_samples", [])

    for item in prediction_samples[:10]:
        actual = item.get("actual", "N/A")
        predicted = item.get("predicted", "N/A")
        add_pdf_line(lines, f"Actual: {actual} | Predicted: {predicted}", 11)

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Smart Recommendations", 14)
    recommendations = report_data.get("recommendations", [])

    for index, recommendation in enumerate(recommendations[:12], start=1):
        add_pdf_line(lines, f"{index}. {recommendation}", 11)

    add_pdf_line(lines, "", 11)
    add_pdf_line(lines, "Prediction Flow", 14)
    prediction_flow = report_data.get("prediction_flow", [])

    for index, step in enumerate(prediction_flow, start=1):
        add_pdf_line(lines, f"{index}. {step}", 11)

    build_simple_pdf(lines, pdf_path)

    return pdf_path


def add_sheet_rows(sheet, rows):
    for row in rows:
        sheet.append(row)

    for cell in sheet[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="6C4CFF")
        cell.alignment = Alignment(horizontal="center")


def autosize_sheet(sheet):
    for column_cells in sheet.columns:
        max_length = 0
        column_letter = column_cells[0].column_letter

        for cell in column_cells:
            value = "" if cell.value is None else str(cell.value)
            max_length = max(max_length, len(value))

        sheet.column_dimensions[column_letter].width = min(max_length + 3, 55)


def create_excel_report(report_data: dict, report_id: str):
    excel_path = REPORT_DIR / f"{report_id}.xlsx"

    workbook = Workbook()

    summary_sheet = workbook.active
    summary_sheet.title = "Summary"

    dataset_details = report_data.get("dataset_details", {})
    model_selection = report_data.get("model_selection", {})

    summary_rows = [
        ["Field", "Value"],
        ["Report ID", report_id],
        ["Algorithm", report_data.get("algorithm", "N/A")],
        ["Model Type", report_data.get("model_type", "N/A")],
        ["Accuracy Score", report_data.get("accuracy_score", "N/A")],
        ["Target Column", dataset_details.get("target_column", "N/A")],
        ["Total Rows", dataset_details.get("total_rows", "N/A")],
        ["Total Columns", dataset_details.get("total_columns", "N/A")],
        ["AI Detected Intent", model_selection.get("ai_detected_intent", "N/A")],
        ["Final Task Type", model_selection.get("final_task_type", "N/A")],
        ["Decision Reason", model_selection.get("decision_reason", "N/A")],
    ]
    add_sheet_rows(summary_sheet, summary_rows)

    metrics_sheet = workbook.create_sheet("Metrics")
    metric_rows = [["Metric", "Value"]]
    for key, value in report_data.get("metrics", {}).items():
        metric_rows.append([key, value])
    add_sheet_rows(metrics_sheet, metric_rows)

    feature_sheet = workbook.create_sheet("Feature Importance")
    feature_rows = [["Feature", "Importance"]]
    for item in report_data.get("feature_importance", []):
        feature_rows.append(
            [
                item.get("feature", "N/A"),
                item.get("importance", "N/A"),
            ]
        )
    add_sheet_rows(feature_sheet, feature_rows)

    prediction_sheet = workbook.create_sheet("Prediction Samples")
    prediction_rows = [["Actual", "Predicted"]]
    for item in report_data.get("prediction_samples", []):
        prediction_rows.append(
            [
                item.get("actual", "N/A"),
                item.get("predicted", "N/A"),
            ]
        )
    add_sheet_rows(prediction_sheet, prediction_rows)

    recommendation_sheet = workbook.create_sheet("Recommendations")
    recommendation_rows = [["No", "Recommendation"]]
    for index, recommendation in enumerate(report_data.get("recommendations", []), start=1):
        recommendation_rows.append([index, recommendation])
    add_sheet_rows(recommendation_sheet, recommendation_rows)

    flow_sheet = workbook.create_sheet("Prediction Flow")
    flow_rows = [["Step", "Description"]]
    for index, step in enumerate(report_data.get("prediction_flow", []), start=1):
        flow_rows.append([index, step])
    add_sheet_rows(flow_sheet, flow_rows)

    for sheet in workbook.worksheets:
        autosize_sheet(sheet)

    workbook.save(excel_path)

    return excel_path


@router.get("/reports")
async def get_all_reports(db: Session = Depends(get_db)):
    datasets = db.query(Dataset).all()

    return [
        {
            "dataset_id": dataset.id,
            "filename": dataset.filename,
            "health_report": dataset.health_report,
        }
        for dataset in datasets
    ]


@router.get("/report/view/{report_id}")
async def view_prediction_report(report_id: str):
    return load_prediction_report(report_id)


@router.get("/report/download/{report_id}")
async def download_prediction_report(report_id: str):
    report_path = get_report_path(report_id)

    if not report_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Prediction report not found.",
        )

    return FileResponse(
        path=report_path,
        media_type="application/json",
        filename=f"ADP_AI_Prediction_Report_{report_id}.json",
    )


@router.get("/report/download-pdf/{report_id}")
async def download_prediction_report_pdf(report_id: str):
    report_data = load_prediction_report(report_id)
    pdf_path = create_pdf_report(report_data, report_id)

    return FileResponse(
        path=pdf_path,
        media_type="application/pdf",
        filename=f"ADP_AI_Prediction_Report_{report_id}.pdf",
    )


@router.get("/report/download-excel/{report_id}")
async def download_prediction_report_excel(report_id: str):
    report_data = load_prediction_report(report_id)
    excel_path = create_excel_report(report_data, report_id)

    return FileResponse(
        path=excel_path,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=f"ADP_AI_Prediction_Report_{report_id}.xlsx",
    )
